#!/bin/bash
echo 'installing..'

echo -n "CF_Key:"
read cfkey
echo "$cfkey" > config/ID

echo -n "NG_Key:"
read ngkey
echo "$ngkey" > config/ID-ng

echo -n "File fake name title:"
read fakename
echo "$fakename" > config/1-alice

echo -n "File fake type:"
read type
echo "$type" > config/2-type

sleep 2
echo 'done'

